resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.uuid | gsub("[{-}]"; "")'
          title: ".name"
          blueprint: '"bitbucketProject"'
          properties:
            private: .is_private
            description: ".description"
            type: .type
            url: ".links.html.href"
  - kind: repository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".name"
          title: ".name"
          blueprint: '"bitbucketRepository"'
          properties:
            readme: file://README.md
            url: ".links.html.href"
            defaultBranch: .mainbranch.name
          relations:
            project: '.project.uuid | gsub("[{-}]"; "")'
